# Generated by Django 4.2.7 on 2025-09-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_admin', '0002_faqcategory_faqpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqpage',
            name='category',
        ),
        migrations.DeleteModel(
            name='SimplePage',
        ),
        migrations.DeleteModel(
            name='FAQCategory',
        ),
        migrations.DeleteModel(
            name='FAQPage',
        ),
    ]
