# Generated by Django 4.2.7 on 2024-07-23 13:35

from django.db import migrations, models
import django.db.models.deletion
import general_models.utils.model_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_count', models.IntegerField(default=0, verbose_name='Счётчик популярности')),
                ('valute_from', models.ForeignKey(limit_choices_to=models.Q(('type_valute', 'Наличные'), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='no_cash_valutes_from', to='general_models.valute', verbose_name='Отдаём')),
                ('valute_to', models.ForeignKey(limit_choices_to=models.Q(('type_valute', 'Наличные'), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='no_cash_valutes_to', to='general_models.valute', verbose_name='Получаем')),
            ],
            options={
                'verbose_name': 'Направление для обмена',
                'verbose_name_plural': 'Направления для обмена',
                'ordering': ['valute_from', 'valute_to'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название обменника(ru)')),
                ('en_name', models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='Название обменника(en)')),
                ('partner_link', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Партнёрская ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус обменника')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP')),
                ('xml_url', models.CharField(max_length=50, verbose_name='Ссылка на XML файл')),
                ('period_for_create', models.IntegerField(blank=True, default=90, help_text='Значение - положительное целое число.При установлении в 0, останавливает задачу периодических добавлений', null=True, validators=[general_models.utils.model_validators.is_positive_validate], verbose_name='Частота добавления в секундах')),
                ('period_for_update', models.IntegerField(blank=True, default=60, help_text='Значение - положительное целое число.При установлении в 0, останавливает задачу периодических обновлений', null=True, validators=[general_models.utils.model_validators.is_positive_validate], verbose_name='Частота обновлений в секундах')),
                ('period_for_parse_black_list', models.IntegerField(blank=True, default=24, help_text='Рекомендуемое значение - 24 часа.\nЗначение - положительное целое число.При установлении в 0, останавливает задачу периодического парсинга чёрного списка', null=True, validators=[general_models.utils.model_validators.is_positive_validate], verbose_name='Частота парсинга чёрного списка в часах')),
                ('direction_black_list', models.ManyToManyField(to='no_cash.direction', verbose_name='Чёрный список')),
            ],
            options={
                'verbose_name': 'Обменник',
                'verbose_name_plural': 'Обменники',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('time_create', models.DateTimeField(blank=True, default=None, help_text='Если оставить поля пустыми, время установится автоматически по московскому часовому поясу', null=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('Опубликован', 'Опубликован'), ('Модерация', 'Модерация'), ('Отклонён', 'Отклонён')], default='Модерация', help_text='При выборе статуса "Отклонён" попадает в очередь на удаление', max_length=20, verbose_name='Статус модерации')),
                ('moderation', models.BooleanField(default=False, verbose_name='Прошел модерацию?')),
                ('grade', models.CharField(choices=[('1', 'Положительный'), ('0', 'Нейтральный'), ('-1', 'Отрицательный')], default='0', verbose_name='Оценка')),
                ('transaction_id', models.CharField(blank=True, default=None, null=True, verbose_name='Номер транзакции')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='no_cash.exchange', verbose_name='Безналичный обменник')),
                ('guest', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_cash_reviews', to='general_models.guest', verbose_name='Гостевой пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-time_create', 'status', 'exchange'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('time_create', models.DateTimeField(blank=True, default=None, help_text='Если оставить поля пустыми, время установится автоматически по московскому часовому поясу', null=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('Опубликован', 'Опубликован'), ('Модерация', 'Модерация'), ('Отклонён', 'Отклонён')], default='Модерация', help_text='При выборе статуса "Отклонён" попадает в очередь на удаление', max_length=20, verbose_name='Статус модерации')),
                ('moderation', models.BooleanField(default=False, verbose_name='Прошел модерацию?')),
                ('grade', models.CharField(choices=[('1', 'Положительный'), ('0', 'Нейтральный'), ('-1', 'Отрицательный')], default='0', verbose_name='Оценка')),
                ('guest', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_cash_comments', to='general_models.guest', verbose_name='Гостевой пользователь')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='no_cash.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-time_create', 'status', 'review'),
            },
        ),
        migrations.CreateModel(
            name='AdminComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('time_create', models.DateTimeField(blank=True, default=None, help_text='Если оставить поля пустыми, время установится автоматически по московскому часовому поясу', null=True, verbose_name='Дата создания')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_comments', to='no_cash.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Комментарий администрации',
                'verbose_name_plural': 'Комментарии администрации',
                'ordering': ('-time_create', 'review'),
            },
        ),
        migrations.CreateModel(
            name='ExchangeDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_count', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сколько отдаём')),
                ('out_count', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сколько получаем')),
                ('min_amount', models.CharField(max_length=50, verbose_name='Минимальное количество')),
                ('max_amount', models.CharField(max_length=50, verbose_name='Максимальное количество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='no_cash.exchange', verbose_name='Обменник')),
                ('valute_from', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_cash_valute_from_directions', to='general_models.valute')),
                ('valute_to', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_cash_valute_to_directions', to='general_models.valute')),
            ],
            options={
                'verbose_name': 'Готовое направление',
                'verbose_name_plural': 'Готовые направления',
                'ordering': ['-is_active', 'exchange', 'valute_from', 'valute_to'],
                'indexes': [models.Index(fields=['exchange', 'is_active'], name='no_cash_exc_exchang_799ef8_idx'), models.Index(fields=['valute_from', 'valute_to', 'is_active'], name='no_cash_exc_valute__b1c965_idx')],
                'unique_together': {('exchange', 'valute_from', 'valute_to')},
            },
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['name'], name='no_cash_exc_name_63fecc_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['en_name'], name='no_cash_exc_en_name_063b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['is_active'], name='no_cash_exc_is_acti_6860a4_idx'),
        ),
        migrations.AddIndex(
            model_name='direction',
            index=models.Index(fields=['valute_from', 'valute_to'], name='no_cash_dir_valute__ec0d69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='direction',
            unique_together={('valute_from', 'valute_to')},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('review', 'username', 'time_create')},
        ),
    ]
