# Generated by Django 4.2.7 on 2024-07-31 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0007_populardirection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='populardirection',
            options={'verbose_name': 'Популярное направление', 'verbose_name_plural': 'Популярные направления'},
        ),
    ]
