# Generated by Django 4.2.7 on 2024-08-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0009_alter_populardirection_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='actual_course',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Актуальный курс обмена'),
        ),
    ]
