# Generated by Django 4.2.7 on 2024-09-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0011_exchange_age_exchange_country_exchange_course_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='course_count',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Количество курсов для обмена'),
        ),
    ]
