# Generated by Django 4.2.7 on 2024-10-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0019_exchangelinkcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangelinkcount',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_cash_exchange_counts', to='no_cash.exchange', verbose_name='Обменник'),
        ),
    ]
