# Generated by Django 4.2.7 on 2025-03-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0023_alter_exchangedirection_in_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='high_aml',
            field=models.BooleanField(default=False, verbose_name='Высокий AML риск?'),
        ),
    ]
