# Generated by Django 4.2.7 on 2025-06-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0026_exchange_time_create'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exchangedirection',
            index=models.Index(fields=['is_active', 'exchange'], name='no_cash_exc_is_acti_fadf2b_idx'),
        ),
    ]
