# Generated by Django 4.2.7 on 2025-08-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0027_exchangedirection_no_cash_exc_is_acti_fadf2b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='active_status',
            field=models.CharField(choices=[('active', 'Активный'), ('unactive', 'Неактивный'), ('disabled', 'Отключен'), ('scam', 'Скам'), ('timeout error', 'Ошибка по таймауту'), ('robot check error', 'Ошибка проверки на робота')], default='Активный', max_length=255, verbose_name='Новый статус обменника'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='timeout',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Кастомный таймаут'),
        ),
    ]
