# Generated by Django 4.2.7 on 2025-08-21 18:45

from django.db import migrations, models
import general_models.utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0030_alter_exchange_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangedirection',
            name='time_action',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='timeout',
            field=models.IntegerField(blank=True, default=None, help_text='Значение должно быть больше 0 и не больше 15', null=True, validators=[general_models.utils.model_validators.custom_timeout_validate], verbose_name='Кастомный таймаут'),
        ),
    ]
