# Generated by Django 4.2.7 on 2025-08-24 08:26

from django.db import migrations, models
import general_models.utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0031_exchangedirection_time_action_alter_exchange_timeout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='period_for_parse_black_list',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='period_for_update',
        ),
        migrations.AlterField(
            model_name='exchange',
            name='period_for_create',
            field=models.IntegerField(blank=True, default=90, help_text='Значение - положительное целое число.При установлении в 0, останавливает периодическую задачу', null=True, validators=[general_models.utils.model_validators.is_positive_validate], verbose_name='Частота периодической задачи в секундах'),
        ),
    ]
