# Generated by Django 4.2.7 on 2025-08-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0032_remove_exchange_period_for_parse_black_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='active_status',
            field=models.CharField(choices=[('Cостояния для изменения', [('active', 'Активный'), ('disabled', 'Отключен'), ('scam', 'Скам'), ('skip', 'Не попадает ни в одну выдачу')]), ('Служебные состояния', [('inactive', 'Неактивный'), ('timeout error', 'Ошибка по таймауту'), ('robot check error', 'Ошибка проверки на робота')])], default='active', max_length=255, verbose_name='Новый статус обменника'),
        ),
    ]
