# Generated by Django 4.2.7 on 2025-09-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0035_alter_comment_unique_together_remove_comment_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedirection',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_directions', to='no_cash.direction', verbose_name='Направление для обмена'),
        ),
        migrations.AlterField(
            model_name='exchangedirection',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions', to='no_cash.exchange', verbose_name='Обменник'),
        ),
        migrations.AlterField(
            model_name='exchangelinkcount',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_counts', to='no_cash.exchange', verbose_name='Обменник'),
        ),
        migrations.AlterField(
            model_name='exchangelinkcount',
            name='exchange_direction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_cash_exchange_counts', to='no_cash.exchangedirection', verbose_name='Готовое направление'),
        ),
    ]
