# Generated by Django 4.2.7 on 2025-11-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0038_alter_direction_options_alter_exchange_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedirection',
            name='max_amount',
            field=models.CharField(blank=True, default=True, max_length=50, null=True, verbose_name='Максимальное количество'),
        ),
        migrations.AlterField(
            model_name='exchangedirection',
            name='min_amount',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Минимальное количество'),
        ),
        migrations.AlterField(
            model_name='newexchangedirection',
            name='max_amount',
            field=models.CharField(blank=True, default=True, max_length=50, null=True, verbose_name='Максимальное количество'),
        ),
        migrations.AlterField(
            model_name='newexchangedirection',
            name='min_amount',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Минимальное количество'),
        ),
    ]
