# Generated by Django 4.2.7 on 2024-05-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='grade',
            field=models.CharField(choices=[('1', 'Положительный'), ('0', 'Нейтральный'), ('-1', 'Отрицательный')], default='0', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.CharField(choices=[('1', 'Положительный'), ('0', 'Нейтральный'), ('-1', 'Отрицательный')], default='0', verbose_name='Оценка'),
        ),
    ]
