# Generated by Django 4.2.7 on 2024-05-16 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0003_guest'),
        ('cash', '0002_alter_comment_time_create_alter_review_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='grade',
            field=models.IntegerField(choices=[(1, 'Положительный'), (0, 'Нейтральный'), (-1, 'Отрицальный')], default=0, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='comment',
            name='guest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_comments', to='general_models.guest', verbose_name='Гостевой пользователь'),
        ),
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.IntegerField(choices=[(1, 'Положительный'), (0, 'Нейтральный'), (-1, 'Отрицальный')], default=0, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='review',
            name='guest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_reviews', to='general_models.guest', verbose_name='Гостевой пользователь'),
        ),
    ]
