# Generated by Django 4.2.7 on 2024-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_review_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP'),
        ),
    ]
