# Generated by Django 4.2.7 on 2024-05-28 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_exchange_is_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('time_create', models.DateTimeField(blank=True, default=None, help_text='Если оставить поля пустыми, время установится автоматически по московскому часовому поясу', null=True, verbose_name='Дата создания')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_comments', to='cash.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Комментарий администрации',
                'verbose_name_plural': 'Комментарии администрации',
                'ordering': ('-time_create', 'review'),
            },
        ),
    ]
