# Generated by Django 4.2.7 on 2024-07-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0006_alter_review_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('directions', models.ManyToManyField(to='cash.direction', verbose_name='Популярные направления')),
            ],
        ),
    ]
