# Generated by Django 4.2.7 on 2024-06-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0006_alter_review_transaction_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='direction',
            index=models.Index(fields=['display_name'], name='cash_direct_display_0504fa_idx'),
        ),
    ]
