# Generated by Django 4.2.7 on 2024-08-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0008_alter_populardirection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populardirection',
            name='directions',
            field=models.ManyToManyField(blank=True, to='cash.direction', verbose_name='Популярные направления'),
        ),
    ]
