# Generated by Django 4.2.7 on 2024-09-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0016_exchange_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='xml_url',
            field=models.CharField(max_length=255, verbose_name='Ссылка на XML файл'),
        ),
    ]
