# Generated by Django 4.2.7 on 2024-10-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0020_alter_exchangelinkcount_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='previous_course',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Актуальный курс обмена'),
        ),
    ]
