# Generated by Django 4.2.7 on 2024-10-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0021_direction_previous_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='previous_course',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Предыдующий курс обмена'),
        ),
    ]
