# Generated by Django 4.2.7 on 2024-11-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0022_alter_direction_previous_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='partner_link',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Партнёрская ссылка'),
        ),
    ]
