# Generated by Django 4.2.7 on 2024-11-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0023_alter_exchange_partner_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedirection',
            name='in_count',
            field=models.DecimalField(decimal_places=5, max_digits=20, verbose_name='Сколько отдаём'),
        ),
        migrations.AlterField(
            model_name='exchangedirection',
            name='out_count',
            field=models.DecimalField(decimal_places=5, max_digits=20, verbose_name='Сколько получаем'),
        ),
    ]
