# Generated by Django 4.2.7 on 2024-12-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0024_alter_exchangedirection_in_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярная'),
        ),
    ]
