# Generated by Django 4.2.7 on 2025-08-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0029_exchange_active_status_exchange_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='time_disable',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отключения'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='active_status',
            field=models.CharField(choices=[('Cостояния для изменения', [('active', 'Активный'), ('disabled', 'Отключен'), ('scam', 'Скам')]), ('Служебные состояния', [('unactive', 'Неактивный'), ('timeout error', 'Ошибка по таймауту'), ('robot check error', 'Ошибка проверки на робота')])], default='active', max_length=255, verbose_name='Новый статус обменника'),
        ),
    ]
