# Generated by Django 4.2.7 on 2025-08-19 11:51

from django.db import migrations, models
import general_models.utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0030_exchange_time_disable_alter_exchange_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='timeout',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[general_models.utils.model_validators.custom_timeout_validate], verbose_name='Кастомный таймаут'),
        ),
    ]
