# Generated by Django 4.2.7 on 2025-09-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0034_alter_exchange_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='en_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Название обменника(en)'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название обменника(ru)'),
        ),
    ]
