# Generated by Django 4.2.7 on 2025-09-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0035_alter_exchange_en_name_alter_exchange_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blacklistelement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='blacklistelement',
            name='city',
        ),
        migrations.RemoveField(
            model_name='blacklistelement',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='review',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='direction_black_list',
        ),
        migrations.DeleteModel(
            name='AdminComment',
        ),
        migrations.DeleteModel(
            name='BlackListElement',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
