# Generated by Django 4.2.7 on 2025-10-05 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0027_admincomment_comment_exchanger_and_more'),
        ('cash', '0037_alter_exchangedirection_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_count', models.IntegerField(default=0, verbose_name='Счётчик популярности')),
                ('actual_course', models.FloatField(blank=True, default=None, null=True, verbose_name='Актуальный курс обмена')),
                ('previous_course', models.FloatField(blank=True, default=None, null=True, verbose_name='Предыдующий курс обмена')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярная')),
                ('valute_from', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_valutes_from', to='general_models.newvalute', to_field='code_name', verbose_name='Отдаём')),
                ('valute_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_valutes_to', to='general_models.newvalute', to_field='code_name', verbose_name='Получаем')),
            ],
            options={
                'verbose_name': 'Направление для обмена (новое)',
                'verbose_name_plural': 'Направления для обмена (новые)',
                'ordering': ['valute_from', 'valute_to'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='popular_count',
            field=models.BigIntegerField(default=0, verbose_name='Счетчик популярности'),
        ),
        migrations.CreateModel(
            name='NewExchangeDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_count', models.DecimalField(decimal_places=5, max_digits=20, verbose_name='Сколько отдаём')),
                ('out_count', models.DecimalField(decimal_places=5, max_digits=20, verbose_name='Сколько получаем')),
                ('min_amount', models.CharField(max_length=50, verbose_name='Минимальное количество')),
                ('max_amount', models.CharField(max_length=50, verbose_name='Максимальное количество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('time_action', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время изменения')),
                ('fromfee', models.FloatField(blank=True, null=True, verbose_name='Процент')),
                ('params', models.CharField(blank=True, max_length=100, null=True, verbose_name='Параметры')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_cash_directions', to='cash.city', verbose_name='Город')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_directions', to='cash.newdirection', verbose_name='Направление для обмена')),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_directions', to='general_models.exchanger', verbose_name='Обменник')),
            ],
            options={
                'verbose_name': 'Готовое направление',
                'verbose_name_plural': 'Готовые направления',
                'ordering': ['-is_active', 'exchange', 'city', 'direction__valute_from', 'direction__valute_to'],
                'unique_together': {('exchange', 'city', 'direction')},
            },
        ),
        migrations.CreateModel(
            name='NewExchangeLinkCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField(default=0, verbose_name='Счетчик просмотров')),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_exchange_counts', to='general_models.exchanger', verbose_name='Обменник')),
                ('exchange_direction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_direction_counts', to='cash.newexchangedirection', verbose_name='Готовое направление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_cash_exchange_counts', to='general_models.guest', verbose_name='Гостевой пользователь')),
            ],
            options={
                'verbose_name': 'Счётчик перехода по ссылке',
                'verbose_name_plural': 'Счётчики перехода по ссылкам',
                'abstract': False,
                'unique_together': {('exchange', 'user', 'exchange_direction')},
            },
        ),
        migrations.AddIndex(
            model_name='newdirection',
            index=models.Index(fields=['valute_from', 'valute_to'], name='cash_newdir_valute__79b762_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newdirection',
            unique_together={('valute_from', 'valute_to')},
        ),
    ]
