# Generated by Django 4.2.7 on 2025-10-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0038_newdirection_city_popular_count_newexchangedirection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['valute_from', 'valute_to'], 'verbose_name': 'Направление для обмена (старое)', 'verbose_name_plural': 'Направления для обмена (старые)'},
        ),
        migrations.AlterModelOptions(
            name='exchange',
            options={'ordering': ['name'], 'verbose_name': 'Обменник (старый)', 'verbose_name_plural': 'Обменники (старые)'},
        ),
        migrations.AlterModelOptions(
            name='exchangedirection',
            options={'ordering': ['-is_active', 'exchange', 'city', 'direction__valute_from', 'direction__valute_to'], 'verbose_name': 'Готовое направление (старое)', 'verbose_name_plural': 'Готовые направления (старые)'},
        ),
        migrations.AlterModelOptions(
            name='exchangelinkcount',
            options={'verbose_name': 'Счётчик перехода по ссылке (старое)', 'verbose_name_plural': 'Счётчики перехода по ссылкам (старые)'},
        ),
        migrations.AlterModelOptions(
            name='newexchangedirection',
            options={'ordering': ['-is_active', 'exchange', 'city', 'direction__valute_from', 'direction__valute_to'], 'verbose_name': 'Готовое направление (новое)', 'verbose_name_plural': 'Готовые направления (новые)'},
        ),
        migrations.AlterModelOptions(
            name='newexchangelinkcount',
            options={'verbose_name': 'Счётчик перехода по ссылке (новое)', 'verbose_name_plural': 'Счётчики перехода по ссылкам (новые)'},
        ),
    ]
