# Generated by Django 4.2.7 on 2025-11-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0053_alter_bankomat_options_and_more'),
        ('cash', '0039_alter_direction_options_alter_exchange_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newexchangedirection',
            name='country_direction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='partners.newcountrydirection', verbose_name='Партерское направление страны'),
        ),
        migrations.AlterField(
            model_name='exchangedirection',
            name='max_amount',
            field=models.CharField(blank=True, default=True, max_length=50, null=True, verbose_name='Максимальное количество'),
        ),
        migrations.AlterField(
            model_name='exchangedirection',
            name='min_amount',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Минимальное количество'),
        ),
        migrations.AlterField(
            model_name='newexchangedirection',
            name='max_amount',
            field=models.CharField(blank=True, default=True, max_length=50, null=True, verbose_name='Максимальное количество'),
        ),
        migrations.AlterField(
            model_name='newexchangedirection',
            name='min_amount',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Минимальное количество'),
        ),
    ]
