# Generated by Django 4.2.7 on 2024-03-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_comment_time_create_alter_review_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='refresh_token',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Рефреш токен'),
        ),
    ]
