# Generated by Django 4.2.7 on 2024-05-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_comment_grade_alter_review_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='transaction_id',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Номер транзакции'),
        ),
    ]
