# Generated by Django 4.2.7 on 2024-04-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_customuser_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='partnercity',
            name='working_days',
            field=models.ManyToManyField(related_name='partner_cities', to='partners.workingday'),
        ),
    ]
