# Generated by Django 4.2.7 on 2024-05-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_review_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='in_count',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Сколько отдаём'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='out_count',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Сколько получаем'),
        ),
    ]
