# Generated by Django 4.2.7 on 2024-04-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_workingday_partnercity_working_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingday',
            options={'verbose_name': 'Рабочий день', 'verbose_name_plural': 'Рабочие дни'},
        ),
        migrations.AddField(
            model_name='partnercity',
            name='time_from',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Работаем с '),
        ),
        migrations.AddField(
            model_name='partnercity',
            name='time_to',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Работаем до '),
        ),
        migrations.AlterField(
            model_name='partnercity',
            name='working_days',
            field=models.ManyToManyField(related_name='partner_cities', to='partners.workingday', verbose_name='Рабочие дни'),
        ),
    ]
