# Generated by Django 4.2.7 on 2024-04-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_alter_comment_time_create_alter_review_time_create'),
        ('partners', '0005_alter_workingday_options_partnercity_time_from_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partnercity',
            unique_together={('exchange', 'city')},
        ),
    ]
