# Generated by Django 4.2.7 on 2024-04-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_alter_partnercity_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='fix_amount',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='percent',
        ),
        migrations.AddField(
            model_name='direction',
            name='in_count',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Сколько отдаём'),
        ),
        migrations.AddField(
            model_name='direction',
            name='out_count',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Сколько получаем'),
        ),
    ]
