# Generated by Django 4.2.7 on 2024-04-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_partnercity_time_update_alter_direction_in_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingday',
            name='code_name',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='Сокращение'),
        ),
    ]
