# Generated by Django 4.2.7 on 2024-05-16 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0003_guest'),
        ('partners', '0009_workingday_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='grade',
            field=models.IntegerField(choices=[(1, 'Положительный'), (0, 'Нейтральный'), (-1, 'Отрицальный')], default=0, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='comment',
            name='guest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_comments', to='general_models.guest', verbose_name='Гостевой пользователь'),
        ),
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.IntegerField(choices=[(1, 'Положительный'), (0, 'Нейтральный'), (-1, 'Отрицальный')], default=0, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='review',
            name='guest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_reviews', to='general_models.guest', verbose_name='Гостевой пользователь'),
        ),
        migrations.AddIndex(
            model_name='workingday',
            index=models.Index(fields=['code_name'], name='partners_wo_code_na_461673_idx'),
        ),
    ]
