# Generated by Django 4.2.7 on 2024-09-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_exchange_age_exchange_country_exchange_course_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='icon_url',
            field=models.FileField(blank=True, default='media/icons/russia.svg', null=True, upload_to='icons/exchange/', verbose_name='Иконка обменника'),
        ),
    ]
