# Generated by Django 4.2.7 on 2024-05-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_comment_grade_comment_guest_review_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
    ]
