# Generated by Django 4.2.7 on 2024-09-26 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0009_guest_chat_link'),
        ('partners', '0014_exchange_icon_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeLinkCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField(default=0, verbose_name='Счетчик просмотров')),
                ('exchange_marker', models.CharField(max_length=255, verbose_name='Маркер')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.exchange', verbose_name='Обменник')),
                ('exchange_direction', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_exchange_counts', to='partners.direction', verbose_name='Готовое направление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_exchange_counts', to='general_models.guest', verbose_name='Гостевой пользователь')),
            ],
            options={
                'verbose_name': 'Счётчик перехода по ссылке',
                'verbose_name_plural': 'Счётчики перехода по ссылкам',
                'abstract': False,
                'unique_together': {('exchange', 'user', 'exchange_direction', 'exchange_marker')},
            },
        ),
    ]
