# Generated by Django 4.2.7 on 2024-10-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0017_alter_exchangelinkcount_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangelinkcount',
            name='exchange_direction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_counts', to='partners.direction', verbose_name='Готовое направление'),
        ),
    ]
