# Generated by Django 4.2.7 on 2024-10-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0022_alter_direction_previous_course'),
        ('partners', '0018_alter_exchangelinkcount_exchange_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercity',
            name='weekend_time_from',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Работаем с (выходные)'),
        ),
        migrations.AddField(
            model_name='partnercity',
            name='weekend_time_to',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Работаем до (выходные)'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='direction',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('valute_from__type_valute', 'Криптовалюта'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Криптовалюта')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Наличные')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='partner_directions', to='cash.direction', verbose_name='Направление'),
        ),
    ]
