# Generated by Django 4.2.7 on 2024-10-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_partnercity_weekend_time_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='max_amount',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Максимальное количество'),
        ),
        migrations.AddField(
            model_name='direction',
            name='min_amount',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Минимальное количество'),
        ),
    ]
