# Generated by Django 4.2.7 on 2024-10-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0021_partnercity_max_amount_partnercity_min_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercity',
            name='max_amount',
            field=models.FloatField(default=None, null=True, verbose_name='Максимальное количество'),
        ),
        migrations.AlterField(
            model_name='partnercity',
            name='min_amount',
            field=models.FloatField(default=None, null=True, verbose_name='Минимальное количество'),
        ),
    ]
