# Generated by Django 4.2.7 on 2024-10-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0022_alter_partnercity_max_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercity',
            name='working_days',
            field=models.ManyToManyField(blank=True, related_name='working_days_cities', to='partners.workingday', verbose_name='Рабочие дни'),
        ),
    ]
