# Generated by Django 4.2.7 on 2024-11-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0023_alter_partnercity_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='partner_link',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Партнёрская ссылка'),
        ),
        migrations.AlterField(
            model_name='partnercity',
            name='max_amount',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Максимальное количество'),
        ),
        migrations.AlterField(
            model_name='partnercity',
            name='min_amount',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Минимальное количество'),
        ),
    ]
