# Generated by Django 4.2.7 on 2024-11-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0024_alter_exchangedirection_in_count_and_more'),
        ('partners', '0025_alter_direction_in_count_alter_direction_out_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_countries', to='cash.country')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_countries', to='partners.exchange')),
            ],
            options={
                'verbose_name': 'Партёрская страна',
                'verbose_name_plural': 'Партёрские страны',
            },
        ),
        migrations.CreateModel(
            name='CountryDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.FloatField(blank=True, default=None, null=True, verbose_name='Минимальное количество')),
                ('max_amount', models.FloatField(blank=True, default=None, null=True, verbose_name='Максимальное количество')),
                ('in_count', models.DecimalField(decimal_places=5, default=None, max_digits=20, null=True, verbose_name='Сколько отдаём')),
                ('out_count', models.DecimalField(decimal_places=5, default=None, max_digits=20, null=True, verbose_name='Сколько получаем')),
                ('time_update', models.DateTimeField(auto_now_add=True, help_text='Время указано по московскому часовому поясу. При не обновлении процентов или фикс. ставки в течении 3 дней, направление становится неактивным.', verbose_name='Последнее обновление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_directions', to='partners.partnercountry', verbose_name='Страна')),
                ('direction', models.ForeignKey(limit_choices_to=models.Q(models.Q(('valute_from__type_valute', 'Криптовалюта'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Криптовалюта')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Наличные')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='partner_country_directions', to='cash.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ('country__exchange', 'country', 'direction'),
                'unique_together': {('country', 'direction')},
            },
        ),
    ]
