# Generated by Django 4.2.7 on 2024-11-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0024_alter_exchangedirection_in_count_and_more'),
        ('partners', '0026_partnercountry_countrydirection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydirection',
            options={'ordering': ('country__exchange', 'country', 'direction'), 'verbose_name': 'Направление страны', 'verbose_name_plural': 'Направления страны'},
        ),
        migrations.AlterModelOptions(
            name='partnercountry',
            options={'ordering': ('exchange', 'country'), 'verbose_name': 'Партнёрская страна', 'verbose_name_plural': 'Партнёрские страны'},
        ),
        migrations.AddField(
            model_name='partnercountry',
            name='has_delivery',
            field=models.BooleanField(default=False, verbose_name='Есть ли доставка?'),
        ),
        migrations.AddField(
            model_name='partnercountry',
            name='has_office',
            field=models.BooleanField(default=False, verbose_name='Есть ли офис?'),
        ),
        migrations.AddField(
            model_name='partnercountry',
            name='max_amount',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Максимальное количество'),
        ),
        migrations.AddField(
            model_name='partnercountry',
            name='min_amount',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Минимальное количество'),
        ),
        migrations.AddField(
            model_name='partnercountry',
            name='time_from',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Работаем с '),
        ),
        migrations.AddField(
            model_name='partnercountry',
            name='time_to',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Работаем до '),
        ),
        migrations.AddField(
            model_name='partnercountry',
            name='time_update',
            field=models.DateTimeField(default=None, null=True, verbose_name='Время последнего обновления'),
        ),
        migrations.AddField(
            model_name='partnercountry',
            name='weekend_time_from',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Работаем с (выходные)'),
        ),
        migrations.AddField(
            model_name='partnercountry',
            name='weekend_time_to',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Работаем до (выходные)'),
        ),
        migrations.AddField(
            model_name='partnercountry',
            name='working_days',
            field=models.ManyToManyField(blank=True, related_name='working_days_counrties', to='partners.workingday', verbose_name='Рабочие дни'),
        ),
        migrations.AlterUniqueTogether(
            name='partnercountry',
            unique_together={('exchange', 'country')},
        ),
    ]
