# Generated by Django 4.2.7 on 2024-11-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0016_alter_valute_type_valute'),
        ('partners', '0027_alter_countrydirection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('valutes', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('type_valute', 'ATM QR')), related_name='bankomats', to='general_models.valute', verbose_name='Валюты')),
            ],
            options={
                'verbose_name': 'Банкомат',
                'verbose_name_plural': 'Банкоматы',
            },
        ),
    ]
