# Generated by Django 4.2.7 on 2024-11-28 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0016_alter_valute_type_valute'),
        ('partners', '0028_bankomat'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRValutePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.customuser', verbose_name='Партнёр')),
                ('valute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_models.valute', verbose_name='Валюта')),
            ],
            options={
                'unique_together': {('partner', 'valute')},
            },
        ),
    ]
