# Generated by Django 4.2.7 on 2024-11-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0029_qrvalutepartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrvalutepartner',
            name='bankomats',
            field=models.ManyToManyField(blank=True, to='partners.bankomat', verbose_name='Банкоматы'),
        ),
    ]
