# Generated by Django 4.2.7 on 2024-12-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0030_qrvalutepartner_bankomats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankomat',
            name='icon_url',
            field=models.FileField(blank=True, default='icons/country/russia.svg', null=True, upload_to='icons/bankomat/', verbose_name='Иконка банкомата'),
        ),
    ]
