# Generated by Django 4.2.7 on 2025-03-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0033_directionrate_countrydirectionrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydirectionrate',
            name='rate_coefficient',
            field=models.FloatField(default=None, null=True, verbose_name='Коэффициент разницы курса от объема'),
        ),
        migrations.AddField(
            model_name='directionrate',
            name='rate_coefficient',
            field=models.FloatField(default=None, null=True, verbose_name='Коэффициент разницы курса от объема'),
        ),
    ]
