# Generated by Django 4.2.7 on 2025-03-25 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0026_exchange_high_aml'),
        ('partners', '0034_countrydirectionrate_rate_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='high_aml',
            field=models.BooleanField(default=False, verbose_name='Высокий AML риск?'),
        ),
        migrations.AlterField(
            model_name='countrydirection',
            name='direction',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('valute_from__type_valute', 'Криптовалюта'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Криптовалюта')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'ATM QR')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='partner_country_directions', to='cash.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='direction',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('valute_from__type_valute', 'Криптовалюта'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Криптовалюта')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'ATM QR')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='partner_directions', to='cash.direction', verbose_name='Направление'),
        ),
    ]
