# Generated by Django 4.2.7 on 2025-04-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('no_cash', '0026_exchange_time_create'),
        ('partners', '0037_exchange_time_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonCashDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.FloatField(blank=True, default=None, null=True, verbose_name='Минимальное количество')),
                ('max_amount', models.FloatField(blank=True, default=None, null=True, verbose_name='Максимальное количество')),
                ('in_count', models.DecimalField(decimal_places=5, default=None, max_digits=20, null=True, verbose_name='Сколько отдаём')),
                ('out_count', models.DecimalField(decimal_places=5, default=None, max_digits=20, null=True, verbose_name='Сколько получаем')),
                ('time_update', models.DateTimeField(auto_now_add=True, help_text='Время указано по московскому часовому поясу. При не обновлении процентов или фикс. ставки в течении 3 дней, направление становится неактивным.', verbose_name='Последнее обновление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_directions', to='no_cash.direction', verbose_name='Направление')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_cash_directions', to='partners.exchange', verbose_name='Обменник')),
            ],
            options={
                'verbose_name': 'Безналичное направление',
                'verbose_name_plural': 'Безналичные направления',
                'ordering': ('exchange', 'direction'),
                'unique_together': {('exchange', 'direction')},
            },
        ),
        migrations.CreateModel(
            name='NonCashDirectionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_count', models.DecimalField(decimal_places=5, default=None, max_digits=20, null=True, verbose_name='Сколько отдаём')),
                ('out_count', models.DecimalField(decimal_places=5, default=None, max_digits=20, null=True, verbose_name='Сколько получаем')),
                ('min_rate_limit', models.FloatField(verbose_name='Минимальный лимит')),
                ('max_rate_limit', models.FloatField(blank=True, default=None, null=True, verbose_name='Максимальный лимит')),
                ('rate_coefficient', models.FloatField(default=None, null=True, verbose_name='Коэффициент разницы курса от объема')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_no_cash_rates', to='partners.exchange', verbose_name='Обменник')),
                ('exchange_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_rates', to='partners.noncashdirection', verbose_name='Готовое направление')),
            ],
            options={
                'verbose_name': 'Объём направления (безналичные)',
                'verbose_name_plural': 'Объёмы направлений (безналичные)',
                'unique_together': {('exchange', 'exchange_direction', 'min_rate_limit')},
            },
        ),
    ]
