# Generated by Django 4.2.7 on 2025-04-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0038_noncashdirection_noncashdirectionrate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='noncashdirectionrate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='noncashdirectionrate',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='noncashdirectionrate',
            name='exchange_direction',
        ),
        migrations.DeleteModel(
            name='NonCashDirection',
        ),
        migrations.DeleteModel(
            name='NonCashDirectionRate',
        ),
    ]
