# Generated by Django 4.2.7 on 2025-07-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0041_noncashexchangelinkcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydirection',
            name='exchange',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_directions', to='partners.exchange', verbose_name='Обменник'),
        ),
        migrations.AddField(
            model_name='direction',
            name='exchange',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_directions', to='partners.exchange', verbose_name='Обменник'),
        ),
    ]
