# Generated by Django 4.2.7 on 2025-07-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0028_exchange_time_create'),
        ('partners', '0042_countrydirection_exchange_direction_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercountry',
            name='exclude_cities',
            field=models.ManyToManyField(to='cash.city', verbose_name='Исключить города из выдачи'),
        ),
    ]
