# Generated by Django 4.2.7 on 2025-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0028_exchange_time_create'),
        ('partners', '0043_partnercountry_exclude_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercountry',
            name='exclude_cities',
            field=models.ManyToManyField(blank=True, null=True, to='cash.city', verbose_name='Исключить города из выдачи'),
        ),
    ]
