# Generated by Django 4.2.7 on 2025-07-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0044_alter_partnercountry_exclude_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercity',
            name='time_update',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время последнего обновления'),
        ),
        migrations.AlterField(
            model_name='partnercountry',
            name='time_update',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время последнего обновления'),
        ),
    ]
