# Generated by Django 4.2.7 on 2025-08-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0045_alter_partnercity_time_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='active_status',
            field=models.CharField(choices=[('active', 'Активный'), ('unactive', 'Неактивный'), ('disabled', 'Отключен'), ('scam', 'Скам'), ('timeout error', 'Ошибка по таймауту'), ('robot check error', 'Ошибка проверки на робота')], default='Активный', max_length=255, verbose_name='Новый статус обменника'),
        ),
    ]
