# Generated by Django 4.2.7 on 2025-09-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0037_alter_exchangedirection_city_and_more'),
        ('no_cash', '0036_alter_exchangedirection_direction_and_more'),
        ('partners', '0050_remove_comment_guest_remove_comment_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydirection',
            name='direction',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('valute_from__type_valute', 'Криптовалюта'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Криптовалюта')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'ATM QR')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_country_directions', to='cash.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='countrydirection',
            name='exchange',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_directions', to='partners.exchange', verbose_name='Обменник'),
        ),
        migrations.AlterField(
            model_name='countrydirectionrate',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_country_rates', to='partners.exchange', verbose_name='Обменник'),
        ),
        migrations.AlterField(
            model_name='countrydirectionrate',
            name='exchange_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_rates', to='partners.countrydirection', verbose_name='Готовое направление'),
        ),
        migrations.AlterField(
            model_name='countryexchangelinkcount',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_country_counts', to='partners.exchange', verbose_name='Обменник'),
        ),
        migrations.AlterField(
            model_name='countryexchangelinkcount',
            name='exchange_direction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_exchange_counts', to='partners.countrydirection', verbose_name='Готовое направление'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_directions', to='partners.partnercity', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='direction',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('valute_from__type_valute', 'Криптовалюта'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Криптовалюта')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'ATM QR')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_directions', to='cash.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='exchange',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_directions', to='partners.exchange', verbose_name='Обменник'),
        ),
        migrations.AlterField(
            model_name='directionrate',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_rates', to='partners.exchange', verbose_name='Обменник'),
        ),
        migrations.AlterField(
            model_name='directionrate',
            name='exchange_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_rates', to='partners.direction', verbose_name='Готовое направление'),
        ),
        migrations.AlterField(
            model_name='exchangelinkcount',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_counts', to='partners.exchange', verbose_name='Обменник'),
        ),
        migrations.AlterField(
            model_name='exchangelinkcount',
            name='exchange_direction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_counts', to='partners.direction', verbose_name='Готовое направление'),
        ),
        migrations.AlterField(
            model_name='noncashdirection',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_directions', to='no_cash.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='noncashdirection',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_cash_directions', to='partners.exchange', verbose_name='Обменник'),
        ),
        migrations.AlterField(
            model_name='noncashdirectionrate',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_no_cash_rates', to='partners.exchange', verbose_name='Обменник'),
        ),
        migrations.AlterField(
            model_name='noncashdirectionrate',
            name='exchange_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_rates', to='partners.noncashdirection', verbose_name='Готовое направление'),
        ),
        migrations.AlterField(
            model_name='noncashexchangelinkcount',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_no_cash_counts', to='partners.exchange', verbose_name='Обменник'),
        ),
        migrations.AlterField(
            model_name='noncashexchangelinkcount',
            name='exchange_direction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_cash_exchange_counts', to='partners.noncashdirection', verbose_name='Готовое направление'),
        ),
    ]
