# Generated by Django 4.2.7 on 2025-10-16 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0039_alter_direction_options_alter_exchange_options_and_more'),
        ('partners', '0052_newbankomat_newcustomuser_newnoncashdirection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankomat',
            options={'verbose_name': 'Банкомат (старый)', 'verbose_name_plural': 'Банкоматы (старые)'},
        ),
        migrations.AlterModelOptions(
            name='countrydirection',
            options={'ordering': ('country__exchange', 'country', 'direction'), 'verbose_name': 'Направление страны (старое)', 'verbose_name_plural': 'Направления страны (старые)'},
        ),
        migrations.AlterModelOptions(
            name='countrydirectionrate',
            options={'verbose_name': 'Объём направления (страны) (старый)', 'verbose_name_plural': 'Объёмы направлений (страны) (старые)'},
        ),
        migrations.AlterModelOptions(
            name='countryexchangelinkcount',
            options={'verbose_name': 'Счётчик перехода по ссылке (страны) (старый)', 'verbose_name_plural': 'Счётчики перехода по ссылкам (страны) (старые)'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Администратор обменника (старый)', 'verbose_name_plural': 'Администраторы обменников (старые)'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ('city__exchange', 'city', 'direction'), 'verbose_name': 'Направление (старое)', 'verbose_name_plural': 'Направления (старые)'},
        ),
        migrations.AlterModelOptions(
            name='directionrate',
            options={'verbose_name': 'Объём направления (старый)', 'verbose_name_plural': 'Объёмы направлений (старые)'},
        ),
        migrations.AlterModelOptions(
            name='exchange',
            options={'ordering': ['name'], 'verbose_name': 'Обменник (старый)', 'verbose_name_plural': 'Обменники (старые)'},
        ),
        migrations.AlterModelOptions(
            name='exchangelinkcount',
            options={'verbose_name': 'Счётчик перехода по ссылке (старое)', 'verbose_name_plural': 'Счётчики перехода по ссылкам (старые)'},
        ),
        migrations.AlterModelOptions(
            name='newcountrydirection',
            options={'ordering': ('country__exchange', 'country', 'direction'), 'verbose_name': 'Направление страны (новое)', 'verbose_name_plural': 'Направления страны (новые)'},
        ),
        migrations.AlterModelOptions(
            name='newcustomuser',
            options={'verbose_name': 'Администратор обменника (новый)', 'verbose_name_plural': 'Администраторы обменников (новые)'},
        ),
        migrations.AlterModelOptions(
            name='newdirection',
            options={'ordering': ('city__exchange', 'city', 'direction'), 'verbose_name': 'Направление (новое)', 'verbose_name_plural': 'Направления (новые)'},
        ),
        migrations.AlterModelOptions(
            name='newnoncashdirection',
            options={'ordering': ('exchange', 'direction'), 'verbose_name': 'Безналичное направление (новое)', 'verbose_name_plural': 'Безналичные направления (новые)'},
        ),
        migrations.AlterModelOptions(
            name='newpartnercity',
            options={'ordering': ('exchange', 'city'), 'verbose_name': 'Партнёрский город (новый)', 'verbose_name_plural': 'Партнёрские города (новые)'},
        ),
        migrations.AlterModelOptions(
            name='newpartnercountry',
            options={'ordering': ('exchange', 'country'), 'verbose_name': 'Партнёрская страна (новая)', 'verbose_name_plural': 'Партнёрские страны (новые)'},
        ),
        migrations.AlterModelOptions(
            name='noncashdirection',
            options={'ordering': ('exchange', 'direction'), 'verbose_name': 'Безналичное направление (старое)', 'verbose_name_plural': 'Безналичные направления (старые)'},
        ),
        migrations.AlterModelOptions(
            name='noncashdirectionrate',
            options={'verbose_name': 'Объём направления (безналичные) (старый)', 'verbose_name_plural': 'Объёмы направлений (безналичные) (старые)'},
        ),
        migrations.AlterModelOptions(
            name='noncashexchangelinkcount',
            options={'verbose_name': 'Счётчик перехода по ссылке (безналичные) (старый)', 'verbose_name_plural': 'Счётчики перехода по ссылкам (безналичные) (старые)'},
        ),
        migrations.AlterModelOptions(
            name='partnercity',
            options={'ordering': ('exchange', 'city'), 'verbose_name': 'Партнёрский город (старый)', 'verbose_name_plural': 'Партнёрские города (старые)'},
        ),
        migrations.AlterModelOptions(
            name='partnercountry',
            options={'ordering': ('exchange', 'country'), 'verbose_name': 'Партнёрская страна (старая)', 'verbose_name_plural': 'Партнёрские страны (старые)'},
        ),
        migrations.AlterField(
            model_name='countrydirection',
            name='direction',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('valute_from__type_valute', 'Криптовалюта'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Криптовалюта')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'ATM QR')), models.Q(('valute_from__type_valute', 'Криптовалюта'), ('valute_to__type_valute', 'ATM QR')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_country_directions', to='cash.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='direction',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('valute_from__type_valute', 'Криптовалюта'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Криптовалюта')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'ATM QR')), models.Q(('valute_from__type_valute', 'Криптовалюта'), ('valute_to__type_valute', 'ATM QR')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_directions', to='cash.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='newcountrydirection',
            name='direction',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('valute_from__type_valute', 'Криптовалюта'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Криптовалюта')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'ATM QR')), models.Q(('valute_from__type_valute', 'Криптовалюта'), ('valute_to__type_valute', 'ATM QR')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_country_directions', to='cash.newdirection', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='newdirection',
            name='direction',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('valute_from__type_valute', 'Криптовалюта'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Криптовалюта')), models.Q(('valute_from__type_valute', 'Наличные'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'Наличные')), models.Q(('valute_from__type_valute', 'Банкинг'), ('valute_to__type_valute', 'ATM QR')), models.Q(('valute_from__type_valute', 'Криптовалюта'), ('valute_to__type_valute', 'ATM QR')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_directions', to='cash.newdirection', verbose_name='Направление'),
        ),
    ]
