# Generated by Django 4.2.7 on 2024-07-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Никнейм')),
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram id')),
                ('first_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Фамилия пользователя')),
                ('language_code', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Язык интерфейса')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Гостевой пользователь',
                'verbose_name_plural': 'Гостевые пользователи',
            },
        ),
        migrations.CreateModel(
            name='MassSendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Массовая рассылка',
                'verbose_name_plural': 'Массовые рассылки',
            },
        ),
        migrations.CreateModel(
            name='PartnerTimeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('unit_time', models.CharField(choices=[('SECOND', 'Секунды'), ('MINUTE', 'Минуты'), ('HOUR', 'Часы'), ('DAY', 'Дни')], max_length=100, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Управление временем партнёрских направлений',
                'verbose_name_plural': 'Управление временем партнёрских направлений',
            },
        ),
        migrations.CreateModel(
            name='Valute',
            fields=[
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название валюты(ru)')),
                ('en_name', models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='Название валюты(en)')),
                ('code_name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Кодовое сокращение')),
                ('type_valute', models.CharField(choices=[('Криптовалюта', 'Криптовалюта'), ('Эл. деньги', 'Эл. деньги'), ('Балансы криптобирж', 'Балансы криптобирж'), ('Банкинг', 'Банкинг'), ('Денежные переводы', 'Денежные переводы'), ('Наличные', 'Наличные')], max_length=30, verbose_name='Тип валюты')),
                ('icon_url', models.FileField(blank=True, null=True, upload_to='icons/valute/', verbose_name='Иконка валюты')),
                ('available_for_partners', models.BooleanField(default=False, verbose_name='Доступно для партнёров')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code_name'],
            },
        ),
        migrations.CreateModel(
            name='MassSendVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='mass_send/videos/', verbose_name='Видео')),
                ('file_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='ID файла')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='general_models.masssendmessage', verbose_name='Cообщение')),
            ],
            options={
                'verbose_name': 'Видео для расслыки',
                'verbose_name_plural': 'Видео для расслыки',
            },
        ),
        migrations.CreateModel(
            name='MassSendImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mass_send/images/', verbose_name='Изображение')),
                ('file_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='ID файла')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='general_models.masssendmessage', verbose_name='Cообщение')),
            ],
            options={
                'verbose_name': 'Изображение для расслыки',
                'verbose_name_plural': 'Изображения для расслыки',
            },
        ),
        migrations.CreateModel(
            name='MassSendFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mass_send/files/', verbose_name='Файл')),
                ('file_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='ID файла')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='general_models.masssendmessage', verbose_name='Cообщение')),
            ],
            options={
                'verbose_name': 'Файл для расслыки',
                'verbose_name_plural': 'Файлы для расслыки',
            },
        ),
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=255, verbose_name='Тип заявки')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('amount', models.CharField(max_length=255, verbose_name='Сумма')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_orders', to='general_models.guest')),
            ],
            options={
                'verbose_name': 'Завка пользователя',
                'verbose_name_plural': 'Заявки пользователей',
                'ordering': ('-time_create',),
            },
        ),
    ]
