# Generated by Django 4.2.7 on 2024-04-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valute',
            name='available_for_partners',
            field=models.BooleanField(default=False, verbose_name='Доступно для партнёров'),
        ),
    ]
