# Generated by Django 4.2.7 on 2024-05-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0002_valute_available_for_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Никнейм')),
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram id')),
            ],
            options={
                'verbose_name': 'Гостевой пользователь',
                'verbose_name_plural': 'Гостевые пользователи',
            },
        ),
    ]
