# Generated by Django 4.2.7 on 2024-06-06 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0004_masssendimage_file_id_masssendvideo_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassSendFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mass_send/files/', verbose_name='Файл')),
                ('file_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='ID файла')),
                ('messsage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='general_models.masssendmessage', verbose_name='Cообщение')),
            ],
        ),
    ]
