# Generated by Django 4.2.7 on 2024-06-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0005_masssendfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masssendfile',
            options={'verbose_name': 'Файл для расслыки', 'verbose_name_plural': 'Файлы для расслыки'},
        ),
        migrations.AlterModelOptions(
            name='masssendimage',
            options={'verbose_name': 'Изображение для расслыки', 'verbose_name_plural': 'Изображения для расслыки'},
        ),
        migrations.AlterModelOptions(
            name='masssendmessage',
            options={'verbose_name': 'Массовая рассылка', 'verbose_name_plural': 'Массовые рассылки'},
        ),
        migrations.AlterModelOptions(
            name='masssendvideo',
            options={'verbose_name': 'Видео для расслыки', 'verbose_name_plural': 'Видео для расслыки'},
        ),
        migrations.RenameField(
            model_name='masssendfile',
            old_name='messsage',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='masssendimage',
            old_name='messsage',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='masssendvideo',
            old_name='messsage',
            new_name='message',
        ),
    ]
