# Generated by Django 4.2.7 on 2024-06-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0006_alter_masssendfile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
        migrations.AddField(
            model_name='guest',
            name='language_code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Язык интерфейса'),
        ),
        migrations.AddField(
            model_name='guest',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Фамилия пользователя'),
        ),
    ]
