# Generated by Django 4.2.7 on 2024-08-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0008_customorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='chat_link',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка на чат'),
        ),
    ]
