# Generated by Django 4.2.7 on 2024-10-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0009_guest_chat_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('reasons', models.CharField(choices=[('Ошибка', 'Ошибка'), ('Проблемма с обменником', 'Проблемма с обменником'), ('Сотрудничество', 'Сотрудничество'), ('Другое', 'Другое')], max_length=255, verbose_name='Причина')),
                ('decription', models.TextField(verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
    ]
