# Generated by Django 4.2.7 on 2024-10-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0011_alter_feedbackform_time_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackform',
            old_name='decription',
            new_name='description',
        ),
    ]
