# Generated by Django 4.2.7 on 2024-10-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0012_rename_decription_feedbackform_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
