# Generated by Django 4.2.7 on 2024-11-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0013_alter_feedbackform_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='utm_source',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Ресурс, с которого пришёл пользователь'),
        ),
    ]
