# Generated by Django 4.2.7 on 2024-11-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0014_guest_utm_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='moderation',
            field=models.BooleanField(default=False, verbose_name='Прошел модерацию'),
        ),
        migrations.AddField(
            model_name='customorder',
            name='status',
            field=models.CharField(choices=[('Модерация', 'Модерация'), ('В обработке', 'В обработке'), ('Завершен', 'Завершен')], default='Модерация', max_length=255, verbose_name='Статус модерации'),
        ),
    ]
