# Generated by Django 4.2.7 on 2024-11-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0015_customorder_moderation_customorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valute',
            name='type_valute',
            field=models.CharField(choices=[('Криптовалюта', 'Криптовалюта'), ('Эл. деньги', 'Эл. деньги'), ('Балансы криптобирж', 'Балансы криптобирж'), ('Банкинг', 'Банкинг'), ('Денежные переводы', 'Денежные переводы'), ('Наличные', 'Наличные'), ('ATM QR', 'ATM QR')], max_length=30, verbose_name='Тип валюты'),
        ),
    ]
