# Generated by Django 4.2.7 on 2024-12-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0016_alter_valute_type_valute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ('username',), 'verbose_name': 'Гостевой пользователь', 'verbose_name_plural': 'Гостевые пользователи'},
        ),
        migrations.AddField(
            model_name='guest',
            name='time_create',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время создания'),
        ),
    ]
