# Generated by Django 4.2.7 on 2024-12-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0017_alter_guest_options_guest_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='valute',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярная'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='time_create',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время добавления'),
        ),
    ]
