# Generated by Django 4.2.7 on 2025-01-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0018_valute_is_popular_alter_guest_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='amount',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Страна'),
        ),
    ]
