# Generated by Django 4.2.7 on 2025-02-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0019_alter_customorder_amount_alter_customorder_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='select_language',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en')], default='ru', max_length=255, verbose_name='Выбранный язык'),
        ),
    ]
