# Generated by Django 4.2.7 on 2025-05-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0020_guest_select_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeAdminOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='Tg id пользователя')),
                ('exchange_name', models.CharField(help_text='Название должно совпадать с названием обменника из НАШЕЙ базы!', max_length=255, verbose_name='Название обменника')),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Заявка на подключение обменника к юзеру',
                'verbose_name_plural': 'Заявки на подключения обменников к юзерам',
            },
        ),
        migrations.CreateModel(
            name='ExchangeAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_marker', models.CharField(max_length=255, verbose_name='Маркер обменника')),
                ('exchange_name', models.CharField(max_length=255, verbose_name='Название обменника')),
                ('exchange_id', models.IntegerField(verbose_name='Id обменника')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_exchanges', to='general_models.guest', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подключенный обменник к юзеру',
                'verbose_name_plural': 'Подключенные обменники к юзерам',
                'unique_together': {('user', 'exchange_marker', 'exchange_id')},
            },
        ),
    ]
