# Generated by Django 4.2.7 on 2025-06-03 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0021_exchangeadminorder_exchangeadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBaseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('time_create', models.DateTimeField(blank=True, default=None, help_text='Если оставить поля пустыми, время установится автоматически по московскому часовому поясу', null=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('Опубликован', 'Опубликован'), ('Модерация', 'Модерация'), ('Отклонён', 'Отклонён')], default='Модерация', help_text='При выборе статуса "Отклонён" попадает в очередь на удаление', max_length=20, verbose_name='Статус модерации')),
                ('moderation', models.BooleanField(default=False, verbose_name='Прошел модерацию?')),
                ('grade', models.CharField(choices=[('1', 'Положительный'), ('0', 'Нейтральный'), ('-1', 'Отрицательный')], default='0', verbose_name='Оценка')),
                ('review_from', models.CharField(choices=[('bestchange', 'bestchange'), ('moneyswap', 'moneyswap')], default='moneyswap', max_length=50, verbose_name='Откуда отзыв')),
                ('exchange_name', models.CharField(max_length=255, verbose_name='Название обменника')),
                ('transaction_id', models.CharField(blank=True, default=None, null=True, verbose_name='Номер транзакции')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='NewBaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('time_create', models.DateTimeField(blank=True, default=None, help_text='Если оставить поля пустыми, время установится автоматически по московскому часовому поясу', null=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('Опубликован', 'Опубликован'), ('Модерация', 'Модерация'), ('Отклонён', 'Отклонён')], default='Модерация', help_text='При выборе статуса "Отклонён" попадает в очередь на удаление', max_length=20, verbose_name='Статус модерации')),
                ('moderation', models.BooleanField(default=False, verbose_name='Прошел модерацию?')),
                ('grade', models.CharField(choices=[('1', 'Положительный'), ('0', 'Нейтральный'), ('-1', 'Отрицательный')], default='0', verbose_name='Оценка')),
                ('review_from', models.CharField(choices=[('bestchange', 'bestchange'), ('moneyswap', 'moneyswap')], default='moneyswap', max_length=50, verbose_name='Откуда отзыв')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='general_models.newbasereview', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='NewBaseAdminComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('time_create', models.DateTimeField(blank=True, default=None, help_text='Если оставить поля пустыми, время установится автоматически по московскому часовому поясу', null=True, verbose_name='Дата создания')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_comments', to='general_models.newbasereview', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Комментарий администрации',
                'verbose_name_plural': 'Комментарии администрации',
            },
        ),
    ]
