# Generated by Django 4.2.7 on 2025-06-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0022_newbasereview_newbasecomment_newbaseadmincomment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newbasereview',
            unique_together={('exchange_name', 'username', 'time_create', 'text')},
        ),
    ]
