# Generated by Django 4.2.7 on 2025-06-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0023_alter_newbasereview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbasecomment',
            name='guest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='general_models.guest', verbose_name='Гостевой пользователь'),
        ),
        migrations.AddField(
            model_name='newbasereview',
            name='guest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='general_models.guest', verbose_name='Гостевой пользователь'),
        ),
    ]
