# Generated by Django 4.2.7 on 2025-06-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0024_newbasecomment_guest_newbasereview_guest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newbasecomment',
            unique_together={('review', 'username', 'time_create')},
        ),
        migrations.AlterUniqueTogether(
            name='newbasereview',
            unique_together={('exchange_name', 'username', 'time_create')},
        ),
    ]
