# Generated by Django 4.2.7 on 2025-07-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0025_alter_newbasecomment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeadmin',
            name='notification',
            field=models.BooleanField(default=True, verbose_name='Уведомления включены?'),
        ),
    ]
