# Generated by Django 4.2.7 on 2025-10-16 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0027_admincomment_comment_exchanger_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admincomment',
            options={'verbose_name': 'Комментарий администрации (новый)', 'verbose_name_plural': 'Комментарии администрации (новые)'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий (новый)', 'verbose_name_plural': 'Комментарии (новые)'},
        ),
        migrations.AlterModelOptions(
            name='exchangeadmin',
            options={'verbose_name': 'Подключенный обменник к юзеру (старый)', 'verbose_name_plural': 'Подключенные обменники к юзерам (старые)'},
        ),
        migrations.AlterModelOptions(
            name='exchangeadminorder',
            options={'verbose_name': 'Заявка на подключение обменника к юзеру (старая)', 'verbose_name_plural': 'Заявки на подключения обменников к юзерам (старые)'},
        ),
        migrations.AlterModelOptions(
            name='newbaseadmincomment',
            options={'verbose_name': 'Комментарий администрации (старый)', 'verbose_name_plural': 'Комментарии администрации (старые)'},
        ),
        migrations.AlterModelOptions(
            name='newbasecomment',
            options={'verbose_name': 'Комментарий (старый)', 'verbose_name_plural': 'Комментарии (старые)'},
        ),
        migrations.AlterModelOptions(
            name='newbasereview',
            options={'verbose_name': 'Отзыв (старый)', 'verbose_name_plural': 'Отзывы (старые)'},
        ),
        migrations.AlterModelOptions(
            name='partnertimeupdate',
            options={'verbose_name': 'Управление временем системных фоновых задач', 'verbose_name_plural': 'Управление временем системных фоновых задач'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв (новый)', 'verbose_name_plural': 'Отзывы (новые)'},
        ),
        migrations.AlterModelOptions(
            name='valute',
            options={'ordering': ['code_name'], 'verbose_name': 'Валюта (старая)', 'verbose_name_plural': 'Валюты (старые)'},
        ),
        migrations.AddField(
            model_name='review',
            name='has_send_to_admin',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено админу'),
        ),
        migrations.AlterField(
            model_name='newexchangeadminorder',
            name='time_create',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Время создания'),
        ),
    ]
