# Generated by Django 4.2.7 on 2025-10-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0028_alter_admincomment_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanger',
            name='is_parse',
            field=models.BooleanField(default=True, verbose_name='Активация фоновой задачи парсинга'),
        ),
    ]
