# Generated by Django 4.2.7 on 2025-11-10 16:08

from django.db import migrations, models
import general_models.utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0029_exchanger_is_parse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchanger',
            name='timeout',
            field=models.IntegerField(blank=True, default=None, help_text='Значение должно быть больше 0 и не больше 15 (по умолчанию используется значение 5)', null=True, validators=[general_models.utils.model_validators.custom_timeout_validate], verbose_name='Кастомный таймаут'),
        ),
    ]
