# Generated by Django 4.2.7 on 2025-11-13 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0040_newexchangedirection_country_direction_and_more'),
        ('general_models', '0030_alter_exchanger_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeLinkCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_display', models.CharField(max_length=255, verbose_name='Направление')),
                ('time_create', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Время создания')),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.city')),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_counts', to='general_models.exchanger', verbose_name='Обменник')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_counts', to='general_models.guest', verbose_name='Гостевой пользователь')),
            ],
            options={
                'verbose_name': 'Счётчик перехода по ссылке (новое)',
                'verbose_name_plural': 'Счётчики перехода по ссылкам (новые)',
            },
        ),
    ]
